// <auto-generated />
using System;
using BackendApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260408084144_fix2_4th_migration")]
    partial class fix2_4th_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendApp.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<int?>("DistrictId1")
                        .HasColumnType("int");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Okato")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Oktmo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId1");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("BackendApp.Models.BaseData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("BaseData");
                });

            modelBuilder.Entity("BackendApp.Models.Communication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("HotLine")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Communications");
                });

            modelBuilder.Entity("BackendApp.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateBegin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("BackendApp.Models.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Kpp")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Ogrn")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("BackendApp.Models.MoDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("OidMo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OidSpmo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Okfs")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long?>("VidMoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VidMoId");

                    b.ToTable("MoDocuments");
                });

            modelBuilder.Entity("BackendApp.Models.OrgType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("OrgTypeName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrgTypes");
                });

            modelBuilder.Entity("BackendApp.Models.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Kbk")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("KfTf")
                        .HasColumnType("int");

                    b.Property<string>("Mcod")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("NalP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("NameE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("NoSmo")
                        .HasColumnType("bit");

                    b.Property<string>("Okopf")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("OrgCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long?>("OrgTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("VedPri")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("OrgTypeId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("BackendApp.Models.OspType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OspType");
                });

            modelBuilder.Entity("BackendApp.Models.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("BackendApp.Models.VidMo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("VidMos");
                });

            modelBuilder.Entity("BackendApp.Models.f031_ermo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommunicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("MoDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("MoDocumentId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("F031_Ermos");
                });

            modelBuilder.Entity("BackendApp.Models.f032_trmo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommunicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateBeginOms")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ExclusionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("MoDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("OspTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("f031_ermoId")
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("f031_ermoParentId")
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("MoDocumentId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OspTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("f031_ermoId");

                    b.HasIndex("f031_ermoParentId");

                    b.ToTable("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.Address", b =>
                {
                    b.HasOne("BackendApp.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId1");

                    b.Navigation("District");
                });

            modelBuilder.Entity("BackendApp.Models.District", b =>
                {
                    b.HasOne("BackendApp.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("BackendApp.Models.MoDocument", b =>
                {
                    b.HasOne("BackendApp.Models.VidMo", "VidMos")
                        .WithMany("MoDocuments")
                        .HasForeignKey("VidMoId");

                    b.Navigation("VidMos");
                });

            modelBuilder.Entity("BackendApp.Models.Organization", b =>
                {
                    b.HasOne("BackendApp.Models.OrgType", "OrgType")
                        .WithMany("Organizations")
                        .HasForeignKey("OrgTypeId");

                    b.Navigation("OrgType");
                });

            modelBuilder.Entity("BackendApp.Models.f031_ermo", b =>
                {
                    b.HasOne("BackendApp.Models.Address", "Address")
                        .WithMany("F031_Ermos")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.MoDocument", "MoDocument")
                        .WithMany()
                        .HasForeignKey("MoDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Organization", "Organization")
                        .WithMany("f031_Ermos")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("BaseData");

                    b.Navigation("Communication");

                    b.Navigation("Document");

                    b.Navigation("MoDocument");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BackendApp.Models.f032_trmo", b =>
                {
                    b.HasOne("BackendApp.Models.Address", "Address")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.MoDocument", "MoDocument")
                        .WithMany()
                        .HasForeignKey("MoDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Organization", "Organization")
                        .WithMany("f032_trmos")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OspType", "OspType")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("OspTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.f032_trmo", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("BackendApp.Models.f031_ermo", "F031_Ermo")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("f031_ermoId");

                    b.HasOne("BackendApp.Models.f031_ermo", "ParentIdMo")
                        .WithMany()
                        .HasForeignKey("f031_ermoParentId");

                    b.Navigation("Address");

                    b.Navigation("BaseData");

                    b.Navigation("Communication");

                    b.Navigation("Document");

                    b.Navigation("F031_Ermo");

                    b.Navigation("MoDocument");

                    b.Navigation("Organization");

                    b.Navigation("OspType");

                    b.Navigation("Parent");

                    b.Navigation("ParentIdMo");
                });

            modelBuilder.Entity("BackendApp.Models.Address", b =>
                {
                    b.Navigation("F031_Ermos");

                    b.Navigation("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.BaseData", b =>
                {
                    b.Navigation("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.OrgType", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("BackendApp.Models.Organization", b =>
                {
                    b.Navigation("f031_Ermos");

                    b.Navigation("f032_trmos");
                });

            modelBuilder.Entity("BackendApp.Models.OspType", b =>
                {
                    b.Navigation("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.VidMo", b =>
                {
                    b.Navigation("MoDocuments");
                });

            modelBuilder.Entity("BackendApp.Models.f031_ermo", b =>
                {
                    b.Navigation("F032_Trmos");
                });
#pragma warning restore 612, 618
        }
    }
}
