// <auto-generated />
using System;
using BackendApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendApp.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressCode")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Oktmo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("BackendApp.Models.BaseData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("BaseData");
                });

            modelBuilder.Entity("BackendApp.Models.Communication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AdditionalContactId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Fax")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("HotLine")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdditionalContactId");

                    b.ToTable("Communications");
                });

            modelBuilder.Entity("BackendApp.Models.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("Code")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DateBegin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("BackendApp.Models.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Kpp")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Ogrn")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("BackendApp.Models.ExpType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("Id");

                    b.ToTable("ExpTypes");
                });

            modelBuilder.Entity("BackendApp.Models.License", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dstart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Dterm")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("BackendApp.Models.OidType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("OidTypes");
                });

            modelBuilder.Entity("BackendApp.Models.OmsType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Id");

                    b.ToTable("OmsTypes");
                });

            modelBuilder.Entity("BackendApp.Models.OrgDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long?>("OidTypeMoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OidTypeSpmoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Okfs")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long?>("VidTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OidTypeMoId");

                    b.HasIndex("OidTypeSpmoId");

                    b.HasIndex("VidTypeId");

                    b.ToTable("OrgDocuments");
                });

            modelBuilder.Entity("BackendApp.Models.OrgName", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("OrgNames");
                });

            modelBuilder.Entity("BackendApp.Models.OrgType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("OrgTypeName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrgTypes");
                });

            modelBuilder.Entity("BackendApp.Models.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Kbk")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("KfTf")
                        .HasColumnType("int");

                    b.Property<string>("Mcod")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<bool?>("NoSmo")
                        .HasColumnType("bit");

                    b.Property<string>("Okopf")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("OrgCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("OrgNameId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrgTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("VedPri")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("OrgNameId");

                    b.HasIndex("OrgTypeId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("BackendApp.Models.OspType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OspType");
                });

            modelBuilder.Entity("BackendApp.Models.PaymentStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Id");

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("BackendApp.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("BackendApp.Models.StatType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Id");

                    b.ToTable("StatTypes");
                });

            modelBuilder.Entity("BackendApp.Models.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Okato")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("BackendApp.Models.VedomType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.HasKey("Id");

                    b.ToTable("VedomType");
                });

            modelBuilder.Entity("BackendApp.Models.VidType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("VidTypes");
                });

            modelBuilder.Entity("BackendApp.Models.f002_InsInclude", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DBegin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("NalP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameE")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("InsIncludes");
                });

            modelBuilder.Entity("BackendApp.Models.f002_smoEmp", b =>
                {
                    b.Property<string>("SmoCod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommunicationId")
                        .HasColumnType("bigint");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("F002_InsIncludeId")
                        .HasColumnType("bigint");

                    b.Property<long>("LicenseId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint");

                    b.HasKey("SmoCod");

                    b.HasIndex("AddressId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("F002_InsIncludeId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PersonId");

                    b.ToTable("F002_SmoEmps");
                });

            modelBuilder.Entity("BackendApp.Models.f002_smo_insAdvice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DEdit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Duved")
                        .HasColumnType("datetime2");

                    b.Property<string>("F002_SmoEmpSmoCod")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("KolZl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearWork")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("F002_SmoEmpSmoCod");

                    b.ToTable("f002_smo_insAdvices");
                });

            modelBuilder.Entity("BackendApp.Models.f005_StatOpl", b =>
                {
                    b.Property<long>("StatusCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StatusCode"));

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("PaymentStatusId")
                        .HasColumnType("bigint");

                    b.HasKey("StatusCode");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("PaymentStatusId");

                    b.ToTable("F005_StatOpls");
                });

            modelBuilder.Entity("BackendApp.Models.f006_VidExp", b =>
                {
                    b.Property<long>("VidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VidId"));

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExpTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("VidId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("ExpTypeId");

                    b.ToTable("F006_VidExps");
                });

            modelBuilder.Entity("BackendApp.Models.f007_Vedom", b =>
                {
                    b.Property<long>("VedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VedId"));

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("VedomTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("VedId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("VedomTypeId");

                    b.ToTable("F007_Vedoms");
                });

            modelBuilder.Entity("BackendApp.Models.f008_TipOms", b =>
                {
                    b.Property<long>("DocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocId"));

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("OmsTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("DocId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("OmsTypeId");

                    b.ToTable("F008_TipOms");
                });

            modelBuilder.Entity("BackendApp.Models.f009_StatZl", b =>
                {
                    b.Property<long>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StatusId"));

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("StatTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("StatusId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("StatTypeId");

                    b.ToTable("F009_StatZls");
                });

            modelBuilder.Entity("BackendApp.Models.f010_Subecti", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<string>("CodeTf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("SubjectId");

                    b.ToTable("F010_Subects");
                });

            modelBuilder.Entity("BackendApp.Models.f019_PersAccOrg", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("F002_SmoEmpId")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("F002_SmoEmpId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("f019_PersAccOrgs");
                });

            modelBuilder.Entity("BackendApp.Models.f031_ermo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommunicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrgDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("OrgDocumentId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("F031_Ermos");
                });

            modelBuilder.Entity("BackendApp.Models.f032_trmo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommunicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateBeginOms")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ExclusionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrgDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("OspTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("f031_ermoId")
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("f031_ermoParentId")
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("OrgDocumentId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OspTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("f031_ermoId");

                    b.HasIndex("f031_ermoParentId");

                    b.ToTable("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.f033_spmo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("CommunicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrgDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrgNameId")
                        .HasColumnType("bigint");

                    b.Property<int>("OspType")
                        .HasColumnType("int");

                    b.Property<long>("OspTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("OrgDocumentId");

                    b.HasIndex("OrgNameId");

                    b.ToTable("F033_Spmos");
                });

            modelBuilder.Entity("BackendApp.Models.f037_licmo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("F031_ErmoId")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("F032_TrmoId")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("LicenseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrgDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("F031_ErmoId");

                    b.HasIndex("F032_TrmoId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("OrgDocumentId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("F037_Licmos");
                });

            modelBuilder.Entity("BackendApp.Models.f038_addrmp", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("F032_TrmoId")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("F033_SpmoId")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("LicenseId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("F032_TrmoId");

                    b.HasIndex("F033_SpmoId");

                    b.HasIndex("LicenseId");

                    b.ToTable("F038_Addrmps");
                });

            modelBuilder.Entity("BackendApp.Models.Address", b =>
                {
                    b.HasOne("BackendApp.Models.District", "District")
                        .WithMany("Addresses")
                        .HasForeignKey("DistrictId");

                    b.Navigation("District");
                });

            modelBuilder.Entity("BackendApp.Models.Communication", b =>
                {
                    b.HasOne("BackendApp.Models.Communication", "AdditionalContact")
                        .WithMany("AdditionalContacts")
                        .HasForeignKey("AdditionalContactId");

                    b.Navigation("AdditionalContact");
                });

            modelBuilder.Entity("BackendApp.Models.District", b =>
                {
                    b.HasOne("BackendApp.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("BackendApp.Models.OrgDocument", b =>
                {
                    b.HasOne("BackendApp.Models.OidType", "OidTypeMo")
                        .WithMany("MoOrgDocuments")
                        .HasForeignKey("OidTypeMoId");

                    b.HasOne("BackendApp.Models.OidType", "OidTypeSpmo")
                        .WithMany("SpmoOrgDocuments")
                        .HasForeignKey("OidTypeSpmoId");

                    b.HasOne("BackendApp.Models.VidType", "VidTypes")
                        .WithMany("MoDocuments")
                        .HasForeignKey("VidTypeId");

                    b.Navigation("OidTypeMo");

                    b.Navigation("OidTypeSpmo");

                    b.Navigation("VidTypes");
                });

            modelBuilder.Entity("BackendApp.Models.Organization", b =>
                {
                    b.HasOne("BackendApp.Models.OrgName", "OrgName")
                        .WithMany()
                        .HasForeignKey("OrgNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OrgType", "OrgType")
                        .WithMany("Organizations")
                        .HasForeignKey("OrgTypeId");

                    b.Navigation("OrgName");

                    b.Navigation("OrgType");
                });

            modelBuilder.Entity("BackendApp.Models.f002_InsInclude", b =>
                {
                    b.HasOne("BackendApp.Models.Organization", null)
                        .WithMany("InsIncludes")
                        .HasForeignKey("OrganizationId");
                });

            modelBuilder.Entity("BackendApp.Models.f002_smoEmp", b =>
                {
                    b.HasOne("BackendApp.Models.Address", "Address")
                        .WithMany("F002_SmoEmps")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany("F002_SmoEmps")
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Communication", "Communication")
                        .WithMany("F002_SmoEmps")
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Document", "Document")
                        .WithMany("F002_SmoEmps")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.f002_InsInclude", "F002_InsInclude")
                        .WithMany()
                        .HasForeignKey("F002_InsIncludeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.License", "License")
                        .WithMany("F002_SmoEmps")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Organization", "Organization")
                        .WithMany("F002_SmoEmps")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Person", "Person")
                        .WithMany("F002_SmoEmps")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("BaseData");

                    b.Navigation("Communication");

                    b.Navigation("Document");

                    b.Navigation("F002_InsInclude");

                    b.Navigation("License");

                    b.Navigation("Organization");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("BackendApp.Models.f002_smo_insAdvice", b =>
                {
                    b.HasOne("BackendApp.Models.f002_smoEmp", "F002_SmoEmp")
                        .WithMany("F002_Smo_InsAdvices")
                        .HasForeignKey("F002_SmoEmpSmoCod")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("F002_SmoEmp");
                });

            modelBuilder.Entity("BackendApp.Models.f005_StatOpl", b =>
                {
                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.PaymentStatus", "PaymentStatus")
                        .WithMany("F005_StatOpls")
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseData");

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("BackendApp.Models.f006_VidExp", b =>
                {
                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.ExpType", "ExpType")
                        .WithMany("F006_VidExps")
                        .HasForeignKey("ExpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseData");

                    b.Navigation("ExpType");
                });

            modelBuilder.Entity("BackendApp.Models.f007_Vedom", b =>
                {
                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.VedomType", "VedomType")
                        .WithMany("f007_Vedoms")
                        .HasForeignKey("VedomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseData");

                    b.Navigation("VedomType");
                });

            modelBuilder.Entity("BackendApp.Models.f008_TipOms", b =>
                {
                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OmsType", "OmsType")
                        .WithMany("f008_TipOms")
                        .HasForeignKey("OmsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseData");

                    b.Navigation("OmsType");
                });

            modelBuilder.Entity("BackendApp.Models.f009_StatZl", b =>
                {
                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.StatType", "StatType")
                        .WithMany("F009_StatZls")
                        .HasForeignKey("StatTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseData");

                    b.Navigation("StatType");
                });

            modelBuilder.Entity("BackendApp.Models.f010_Subecti", b =>
                {
                    b.HasOne("BackendApp.Models.Address", null)
                        .WithMany("F010_Subects")
                        .HasForeignKey("AddressId");

                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseData");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("BackendApp.Models.f019_PersAccOrg", b =>
                {
                    b.HasOne("BackendApp.Models.Address", "Address")
                        .WithMany("F019_PersAccOrgs")
                        .HasForeignKey("AddressId");

                    b.HasOne("BackendApp.Models.f002_smoEmp", "F002_SmoEmp")
                        .WithMany("F019_PersAccOrgs")
                        .HasForeignKey("F002_SmoEmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Organization", "Organization")
                        .WithMany("F019_PersAccOrgs")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Address");

                    b.Navigation("F002_SmoEmp");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BackendApp.Models.f031_ermo", b =>
                {
                    b.HasOne("BackendApp.Models.Address", "Address")
                        .WithMany("F031_Ermos")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany("F031_Ermos")
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Communication", "Communication")
                        .WithMany("F031_Ermos")
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OrgDocument", "OrgDocument")
                        .WithMany("F031_Ermos")
                        .HasForeignKey("OrgDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Organization", "Organization")
                        .WithMany("f031_Ermos")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("BaseData");

                    b.Navigation("Communication");

                    b.Navigation("Document");

                    b.Navigation("OrgDocument");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BackendApp.Models.f032_trmo", b =>
                {
                    b.HasOne("BackendApp.Models.Address", "Address")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OrgDocument", "OrgDocument")
                        .WithMany()
                        .HasForeignKey("OrgDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Organization", "Organization")
                        .WithMany("f032_trmos")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OspType", "OspType")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("OspTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.f032_trmo", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("BackendApp.Models.f031_ermo", "F031_Ermo")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("f031_ermoId");

                    b.HasOne("BackendApp.Models.f031_ermo", "ParentIdMo")
                        .WithMany()
                        .HasForeignKey("f031_ermoParentId");

                    b.Navigation("Address");

                    b.Navigation("BaseData");

                    b.Navigation("Communication");

                    b.Navigation("Document");

                    b.Navigation("F031_Ermo");

                    b.Navigation("OrgDocument");

                    b.Navigation("Organization");

                    b.Navigation("OspType");

                    b.Navigation("Parent");

                    b.Navigation("ParentIdMo");
                });

            modelBuilder.Entity("BackendApp.Models.f033_spmo", b =>
                {
                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OrgDocument", "OrgDocument")
                        .WithMany()
                        .HasForeignKey("OrgDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OrgName", "OrgName")
                        .WithMany()
                        .HasForeignKey("OrgNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseData");

                    b.Navigation("Communication");

                    b.Navigation("OrgDocument");

                    b.Navigation("OrgName");
                });

            modelBuilder.Entity("BackendApp.Models.f037_licmo", b =>
                {
                    b.HasOne("BackendApp.Models.f031_ermo", "F031_Ermo")
                        .WithMany("F037_Licmos")
                        .HasForeignKey("F031_ErmoId");

                    b.HasOne("BackendApp.Models.f032_trmo", "F032_Trmo")
                        .WithMany("F037_Licmos")
                        .HasForeignKey("F032_TrmoId");

                    b.HasOne("BackendApp.Models.License", "License")
                        .WithMany("F037_Licmos")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OrgDocument", "OrgDocument")
                        .WithMany("F037_Licmos")
                        .HasForeignKey("OrgDocumentId");

                    b.HasOne("BackendApp.Models.Organization", "Organization")
                        .WithMany("F037_Licmos")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("F031_Ermo");

                    b.Navigation("F032_Trmo");

                    b.Navigation("License");

                    b.Navigation("OrgDocument");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BackendApp.Models.f038_addrmp", b =>
                {
                    b.HasOne("BackendApp.Models.Address", "Address")
                        .WithMany("F038_Addrmp")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.f032_trmo", "F032_Trmo")
                        .WithMany("F038_Addrmp")
                        .HasForeignKey("F032_TrmoId");

                    b.HasOne("BackendApp.Models.f033_spmo", "F033_Spmo")
                        .WithMany("F038_Addrmp")
                        .HasForeignKey("F033_SpmoId");

                    b.HasOne("BackendApp.Models.License", "License")
                        .WithMany("F038_Addrmps")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("BaseData");

                    b.Navigation("F032_Trmo");

                    b.Navigation("F033_Spmo");

                    b.Navigation("License");
                });

            modelBuilder.Entity("BackendApp.Models.Address", b =>
                {
                    b.Navigation("F002_SmoEmps");

                    b.Navigation("F010_Subects");

                    b.Navigation("F019_PersAccOrgs");

                    b.Navigation("F031_Ermos");

                    b.Navigation("F032_Trmos");

                    b.Navigation("F038_Addrmp");
                });

            modelBuilder.Entity("BackendApp.Models.BaseData", b =>
                {
                    b.Navigation("F002_SmoEmps");

                    b.Navigation("F031_Ermos");

                    b.Navigation("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.Communication", b =>
                {
                    b.Navigation("AdditionalContacts");

                    b.Navigation("F002_SmoEmps");

                    b.Navigation("F031_Ermos");
                });

            modelBuilder.Entity("BackendApp.Models.District", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("BackendApp.Models.Document", b =>
                {
                    b.Navigation("F002_SmoEmps");
                });

            modelBuilder.Entity("BackendApp.Models.ExpType", b =>
                {
                    b.Navigation("F006_VidExps");
                });

            modelBuilder.Entity("BackendApp.Models.License", b =>
                {
                    b.Navigation("F002_SmoEmps");

                    b.Navigation("F037_Licmos");

                    b.Navigation("F038_Addrmps");
                });

            modelBuilder.Entity("BackendApp.Models.OidType", b =>
                {
                    b.Navigation("MoOrgDocuments");

                    b.Navigation("SpmoOrgDocuments");
                });

            modelBuilder.Entity("BackendApp.Models.OmsType", b =>
                {
                    b.Navigation("f008_TipOms");
                });

            modelBuilder.Entity("BackendApp.Models.OrgDocument", b =>
                {
                    b.Navigation("F031_Ermos");

                    b.Navigation("F037_Licmos");
                });

            modelBuilder.Entity("BackendApp.Models.OrgType", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("BackendApp.Models.Organization", b =>
                {
                    b.Navigation("F002_SmoEmps");

                    b.Navigation("F019_PersAccOrgs");

                    b.Navigation("F037_Licmos");

                    b.Navigation("InsIncludes");

                    b.Navigation("f031_Ermos");

                    b.Navigation("f032_trmos");
                });

            modelBuilder.Entity("BackendApp.Models.OspType", b =>
                {
                    b.Navigation("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.PaymentStatus", b =>
                {
                    b.Navigation("F005_StatOpls");
                });

            modelBuilder.Entity("BackendApp.Models.Person", b =>
                {
                    b.Navigation("F002_SmoEmps");
                });

            modelBuilder.Entity("BackendApp.Models.StatType", b =>
                {
                    b.Navigation("F009_StatZls");
                });

            modelBuilder.Entity("BackendApp.Models.VedomType", b =>
                {
                    b.Navigation("f007_Vedoms");
                });

            modelBuilder.Entity("BackendApp.Models.VidType", b =>
                {
                    b.Navigation("MoDocuments");
                });

            modelBuilder.Entity("BackendApp.Models.f002_smoEmp", b =>
                {
                    b.Navigation("F002_Smo_InsAdvices");

                    b.Navigation("F019_PersAccOrgs");
                });

            modelBuilder.Entity("BackendApp.Models.f031_ermo", b =>
                {
                    b.Navigation("F032_Trmos");

                    b.Navigation("F037_Licmos");
                });

            modelBuilder.Entity("BackendApp.Models.f032_trmo", b =>
                {
                    b.Navigation("F037_Licmos");

                    b.Navigation("F038_Addrmp");
                });

            modelBuilder.Entity("BackendApp.Models.f033_spmo", b =>
                {
                    b.Navigation("F038_Addrmp");
                });
#pragma warning restore 612, 618
        }
    }
}
