// <auto-generated />
using System;
using BackendApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendApp.Models.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AddressCode")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<long?>("DistrictId")
                        .HasColumnType("bigint");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Okato")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Oktmo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("BackendApp.Models.BaseData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("Id");

                    b.ToTable("BaseData");
                });

            modelBuilder.Entity("BackendApp.Models.Communication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Fax")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("HotLine")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Communications");
                });

            modelBuilder.Entity("BackendApp.Models.District", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DateBegin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("SubjectId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("BackendApp.Models.Document", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Kpp")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Ogrn")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("BackendApp.Models.OidType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("OidTypes");
                });

            modelBuilder.Entity("BackendApp.Models.OrgDocument", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long?>("OidTypeMoId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OidTypeSpmoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Okfs")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long?>("VidTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OidTypeMoId");

                    b.HasIndex("OidTypeSpmoId");

                    b.HasIndex("VidTypeId");

                    b.ToTable("OrgDocuments");
                });

            modelBuilder.Entity("BackendApp.Models.OrgType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("OrgTypeName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OrgTypes");
                });

            modelBuilder.Entity("BackendApp.Models.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Kbk")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("KfTf")
                        .HasColumnType("int");

                    b.Property<string>("Mcod")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int?>("NalP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(2500)
                        .HasColumnType("nvarchar(2500)");

                    b.Property<string>("NameE")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool?>("NoSmo")
                        .HasColumnType("bit");

                    b.Property<string>("Okopf")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("OrgCode")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long?>("OrgTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VedPri")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("OrgTypeId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("BackendApp.Models.OspType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OspType");
                });

            modelBuilder.Entity("BackendApp.Models.Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("BackendApp.Models.VidType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("VidTypes");
                });

            modelBuilder.Entity("BackendApp.Models.f031_ermo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommunicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrgDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("OrgDocumentId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("F031_Ermos");
                });

            modelBuilder.Entity("BackendApp.Models.f032_trmo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<long>("CommunicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateBeginOms")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<long>("DocumentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ExclusionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InclusionDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("OrgDocumentId")
                        .HasColumnType("bigint");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<long>("OspTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("f031_ermoId")
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("f031_ermoParentId")
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("OrgDocumentId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OspTypeId");

                    b.HasIndex("ParentId");

                    b.HasIndex("f031_ermoId");

                    b.HasIndex("f031_ermoParentId");

                    b.ToTable("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.f033_spmo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<long>("CommunicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<long>("OrgDocumentId")
                        .HasColumnType("bigint");

                    b.Property<int>("OspType")
                        .HasColumnType("int");

                    b.Property<long>("OspTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortName")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("CommunicationId");

                    b.HasIndex("OrgDocumentId");

                    b.ToTable("F033_Spmos");
                });

            modelBuilder.Entity("BackendApp.Models.f038_addrmp", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(19)
                        .HasColumnType("nvarchar(19)");

                    b.Property<long>("AddressId")
                        .HasColumnType("bigint");

                    b.Property<long>("BaseDataId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DateBeg")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("F032_TrmoId")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("F033_SpmoId")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<string>("LicenseNum")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BaseDataId");

                    b.HasIndex("F032_TrmoId");

                    b.HasIndex("F033_SpmoId");

                    b.ToTable("F038_Addrmps");
                });

            modelBuilder.Entity("BackendApp.Models.Address", b =>
                {
                    b.HasOne("BackendApp.Models.District", "District")
                        .WithMany("Addresses")
                        .HasForeignKey("DistrictId");

                    b.Navigation("District");
                });

            modelBuilder.Entity("BackendApp.Models.District", b =>
                {
                    b.HasOne("BackendApp.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("BackendApp.Models.OrgDocument", b =>
                {
                    b.HasOne("BackendApp.Models.OidType", "OidTypeMo")
                        .WithMany()
                        .HasForeignKey("OidTypeMoId");

                    b.HasOne("BackendApp.Models.OidType", "OidTypeSpmo")
                        .WithMany()
                        .HasForeignKey("OidTypeSpmoId");

                    b.HasOne("BackendApp.Models.VidType", "VidTypes")
                        .WithMany("MoDocuments")
                        .HasForeignKey("VidTypeId");

                    b.Navigation("OidTypeMo");

                    b.Navigation("OidTypeSpmo");

                    b.Navigation("VidTypes");
                });

            modelBuilder.Entity("BackendApp.Models.Organization", b =>
                {
                    b.HasOne("BackendApp.Models.OrgType", "OrgType")
                        .WithMany("Organizations")
                        .HasForeignKey("OrgTypeId");

                    b.Navigation("OrgType");
                });

            modelBuilder.Entity("BackendApp.Models.f031_ermo", b =>
                {
                    b.HasOne("BackendApp.Models.Address", "Address")
                        .WithMany("F031_Ermos")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OrgDocument", "OrgDocument")
                        .WithMany()
                        .HasForeignKey("OrgDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Organization", "Organization")
                        .WithMany("f031_Ermos")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("BaseData");

                    b.Navigation("Communication");

                    b.Navigation("Document");

                    b.Navigation("OrgDocument");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("BackendApp.Models.f032_trmo", b =>
                {
                    b.HasOne("BackendApp.Models.Address", "Address")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OrgDocument", "OrgDocument")
                        .WithMany()
                        .HasForeignKey("OrgDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Organization", "Organization")
                        .WithMany("f032_trmos")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OspType", "OspType")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("OspTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.f032_trmo", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.HasOne("BackendApp.Models.f031_ermo", "F031_Ermo")
                        .WithMany("F032_Trmos")
                        .HasForeignKey("f031_ermoId");

                    b.HasOne("BackendApp.Models.f031_ermo", "ParentIdMo")
                        .WithMany()
                        .HasForeignKey("f031_ermoParentId");

                    b.Navigation("Address");

                    b.Navigation("BaseData");

                    b.Navigation("Communication");

                    b.Navigation("Document");

                    b.Navigation("F031_Ermo");

                    b.Navigation("OrgDocument");

                    b.Navigation("Organization");

                    b.Navigation("OspType");

                    b.Navigation("Parent");

                    b.Navigation("ParentIdMo");
                });

            modelBuilder.Entity("BackendApp.Models.f033_spmo", b =>
                {
                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.Communication", "Communication")
                        .WithMany()
                        .HasForeignKey("CommunicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.OrgDocument", "OrgDocument")
                        .WithMany()
                        .HasForeignKey("OrgDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseData");

                    b.Navigation("Communication");

                    b.Navigation("OrgDocument");
                });

            modelBuilder.Entity("BackendApp.Models.f038_addrmp", b =>
                {
                    b.HasOne("BackendApp.Models.Address", "Address")
                        .WithMany("F038_Addrmp")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.BaseData", "BaseData")
                        .WithMany()
                        .HasForeignKey("BaseDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendApp.Models.f032_trmo", "F032_Trmo")
                        .WithMany("F038_Addrmp")
                        .HasForeignKey("F032_TrmoId");

                    b.HasOne("BackendApp.Models.f033_spmo", "F033_Spmo")
                        .WithMany("F038_Addrmp")
                        .HasForeignKey("F033_SpmoId");

                    b.Navigation("Address");

                    b.Navigation("BaseData");

                    b.Navigation("F032_Trmo");

                    b.Navigation("F033_Spmo");
                });

            modelBuilder.Entity("BackendApp.Models.Address", b =>
                {
                    b.Navigation("F031_Ermos");

                    b.Navigation("F032_Trmos");

                    b.Navigation("F038_Addrmp");
                });

            modelBuilder.Entity("BackendApp.Models.BaseData", b =>
                {
                    b.Navigation("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.District", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("BackendApp.Models.OrgType", b =>
                {
                    b.Navigation("Organizations");
                });

            modelBuilder.Entity("BackendApp.Models.Organization", b =>
                {
                    b.Navigation("f031_Ermos");

                    b.Navigation("f032_trmos");
                });

            modelBuilder.Entity("BackendApp.Models.OspType", b =>
                {
                    b.Navigation("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.VidType", b =>
                {
                    b.Navigation("MoDocuments");
                });

            modelBuilder.Entity("BackendApp.Models.f031_ermo", b =>
                {
                    b.Navigation("F032_Trmos");
                });

            modelBuilder.Entity("BackendApp.Models.f032_trmo", b =>
                {
                    b.Navigation("F038_Addrmp");
                });

            modelBuilder.Entity("BackendApp.Models.f033_spmo", b =>
                {
                    b.Navigation("F038_Addrmp");
                });
#pragma warning restore 612, 618
        }
    }
}
